[alice]
Q = [["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[bob]
Q = [["alice", "carol"],
     ["alice", "dave"],
     ["carol", "dave"]]

[carol]
Q = [["alice", "bob"],
     ["alice", "dave"],
     ["bob", "dave"]]

[dave]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["bob", "carol"]]
