[alice]
Q = [{m = 2, s = ["bob", "carol", "dave"]}]

[bob]
Q = [{m = 2, s = ["alice", "carol", "dave"]}]

[carol]
Q = [{m = 2, s = ["alice", "bob", "dave"]}]

[dave]
Q = [{m = 2, s = ["alice", "bob", "carol"]}]
