[alice]
Q = [{m = 2, s = ["bob", "carol", "dave"]}]

[bob]
Q = [{m = 2, s = ["alice", "carol", "dave"]}]

[carol]
Q = [{m = 2, s = ["alice", "bob", "dave"]}]

[dave]
Q = [{m = 2, s = ["alice", "bob", "carol"]}]

[elsie]
Q = [{m = 2, s = ["alice", "bob", "carol", "dave"]}]

[fred]
Q = [{m = 2, s = ["alice", "bob", "carol", "dave"]}]

[gwen]
Q = [{m = 2, s = ["alice", "bob", "carol", "dave"]}]

[hank]
Q = [{m = 2, s = ["alice", "bob", "carol", "dave"]}]

[inez]
Q = [{m = 2, s = ["elsie", "fred", "gwen", "hank"]}]

[john]
Q = [{m = 2, s = ["elsie", "fred", "gwen", "hank"]}]
