[alice]
Q = [["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[bob]
Q = [["alice", "carol"],
     ["alice", "dave"],
     ["carol", "dave"]]

[carol]
Q = [["alice", "bob"],
     ["alice", "dave"],
     ["bob", "dave"]]

[dave]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["bob", "carol"]]

[elsie]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["alice", "dave"],
     ["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[fred]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["alice", "dave"],
     ["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[gwen]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["alice", "dave"],
     ["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[hank]
Q = [["alice", "bob"],
     ["alice", "carol"],
     ["alice", "dave"],
     ["bob", "carol"],
     ["bob", "dave"],
     ["carol", "dave"]]

[inez]
Q = [["elsie", "fred"],
     ["elsie", "gwen"],
     ["elsie", "hank"],
     ["fred", "gwen"],
     ["fred", "hank"],
     ["gwen", "hank"]]

[john]
Q = [["elsie", "fred"],
     ["elsie", "gwen"],
     ["elsie", "hank"],
     ["fred", "gwen"],
     ["fred", "hank"],
     ["gwen", "hank"]]
