[alice]
Q = [{m = 2, s = ["bob", "carol"]},
     {m = 2, s = ["dave", "elsie"]}]

[bob]
Q = [{m = 2, s = ["alice", "carol"]}]

[carol]
Q = [{m = 2, s = ["alice", "bob"]}]

[dave]
Q = [{m = 2, s = ["alice", "elsie"]}]

[elsie]
Q = [{m = 2, s = ["alice", "dave"]}]
