[alice]
Q = {t = 1, m = [{t = 2, m = [{n = "bob"}, {n = "carol"}]},
                 {t = 2, m = [{n = "dave"}, {n = "elsie"}]}]}

[bob]
Q = {t = 2, m = [{n = "alice"}, {n = "carol"}]}

[carol]
Q = {t = 2, m = [{n = "alice"}, {n = "bob"}]}

[dave]
Q = {t = 2, m = [{n = "alice"}, {n = "elsie"}]}

[elsie]
Q = {t = 2, m = [{n = "alice"}, {n = "dave"}]}
